import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css';
import { getSortedPostData } from '@/lib/lector';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps(){
  const allPostsData = getSortedPostData();
  return{
    props:{
      allPostsData,
    },
  };
}

export default function Home({allPostsData}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>Hola Xoup</h3>
        <ul>
          {allPostsData.map(({id,fecha,titulo}) =>(
            <li key={id}>
              <Link href={`/posts/${id}`}>{titulo}</Link>
                <p>{fecha}</p>
            </li>
          ))
          }
        </ul>
      </main>
    </>
  )
}
